/**
 ******************************************************************************
 * @file           : main.c
 * @author     : Auto-generated by STM32CubeIDE
 * @brief        : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*******************************************************************************
 *                              					Include Libraries						                       	*
 *******************************************************************************/

#include "APP_INTERFACE.h"

/*******************************************************************************
 *                              						APP Execution											   	*
 *******************************************************************************/

int main(void)
{
	APP_voidSystemInitialization();
	while(1)
	{
		APP_voidExecution();
	}
}
