/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "../Inc/MCAL/RCC_DRIVER/RCC_INTERFACE.h"
#include "../Inc/MCAL/SYSTICK_DRIVER/SYSTICK_INTERFACE.h"
#include "../Inc/MCAL/GPIO_DRIVER/GPIO_INTERFACE.h"


void FuncISR(void)
{
	static u8 counter = 0;
	counter++;
	if(counter == 1)
	{
		GPIO_voidSetPinValue(PIN_0, PORT_A, GPIO_ODR_HIGH);
	}
	else if(counter == 2)
	{
		GPIO_voidSetPinValue(PIN_0, PORT_A, GPIO_ODR_LOW);
		counter = 0;
	}
}





int main(void)
{
	RCC_voidInitialization();
	RCC_voidPeripheralClockEnable(2,2);
	GPIO_voidSetPinDirection(PIN_0, PORT_A, OUTSPEED_10MHZ_PUSHPULL);
	SYSTICK_voidInitialization();
	while(1)
	{
		SYSTICK_voidSetDelay_ms_ISR(1500, FuncISR);
	}

}
